name: hospital_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0
  web_socket_channel: ^3.0.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  path: ^1.9.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
